# Generated by Django 5.1 on 2024-10-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_lawyer_phone'),
        ('users', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='selected_lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='lawyers.lawyer'),
        ),
    ]
