# Generated by Django 5.1 on 2024-10-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='bio',
            field=models.TextField(default='sheria ni msumeno ukatao kuwili', max_length=255),
        ),
    ]
