# Generated by Django 5.1 on 2024-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_lawyer_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='cases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
