# Generated by Django 5.1 on 2024-10-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_appointment_casemanagement_payment_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(default='+254 ', max_length=15),
        ),
    ]
