# Generated by Django 5.1 on 2024-11-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
