# Generated by Django 5.1 on 2024-11-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_alter_lawyer_options_lawyer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(default='example@gmail.com', help_text='example@gmail.com', max_length=254, unique=True),
        ),
    ]
