# Generated by Django 5.1 on 2024-11-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0010_lawyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='email',
        ),
    ]
